#############################################################################
# Makefile for building: WebKit
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  WebKit.pro
# Template: subdirs
# Command: /opt/qt510/bin/qmake -o Makefile WebKit.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /opt/qt510/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/qt510/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/qt510/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = WebKit1.0.0
DISTDIR = /home/mnutt/src/qtwebkit/.obj/WebKit1.0.0
SUBTARGETS    = 



Makefile: WebKit.pro .qmake.conf /opt/qt510/mkspecs/linux-g++/qmake.conf /opt/qt510/mkspecs/features/spec_pre.prf \
		/opt/qt510/mkspecs/common/unix.conf \
		/opt/qt510/mkspecs/common/linux.conf \
		/opt/qt510/mkspecs/common/sanitize.conf \
		/opt/qt510/mkspecs/common/gcc-base.conf \
		/opt/qt510/mkspecs/common/gcc-base-unix.conf \
		/opt/qt510/mkspecs/common/g++-base.conf \
		/opt/qt510/mkspecs/common/g++-unix.conf \
		/opt/qt510/mkspecs/qconfig.pri \
		/opt/qt510/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt510/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_core.pri \
		/opt/qt510/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt510/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt510/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_location.pri \
		/opt/qt510/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt510/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt510/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_network.pri \
		/opt/qt510/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt510/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt510/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt510/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt510/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt510/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt510/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt510/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt510/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt510/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_script.pri \
		/opt/qt510/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt510/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt510/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt510/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt510/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt510/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt510/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt510/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt510/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt510/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt510/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt510/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt510/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt510/mkspecs/features/qt_functions.prf \
		/opt/qt510/mkspecs/features/qt_config.prf \
		/opt/qt510/mkspecs/linux-g++/qmake.conf \
		/opt/qt510/mkspecs/features/spec_post.prf \
		/opt/qt510/mkspecs/qmodule.pri \
		/opt/qt510/mkspecs/features/qt_build_config.prf \
		.qmake.conf \
		/opt/qt510/mkspecs/features/exclusive_builds.prf \
		/opt/qt510/mkspecs/features/toolchain.prf \
		/opt/qt510/mkspecs/features/default_pre.prf \
		Tools/qmake/mkspecs/features/functions.prf \
		/opt/qt510/mkspecs/features/resolve_config.prf \
		/opt/qt510/mkspecs/features/default_post.prf \
		/opt/qt510/mkspecs/features/exceptions_off.prf \
		/opt/qt510/mkspecs/features/qt_example_installs.prf \
		/opt/qt510/mkspecs/features/qt_docs_targets.prf \
		/opt/qt510/mkspecs/features/unix/largefile.prf \
		/opt/qt510/mkspecs/features/warn_on.prf \
		/opt/qt510/mkspecs/features/qmake_use.prf \
		/opt/qt510/mkspecs/features/file_copies.prf \
		/opt/qt510/mkspecs/features/qt_build_extra.prf \
		/opt/qt510/mkspecs/features/testcase_targets.prf \
		/opt/qt510/mkspecs/features/yacc.prf \
		/opt/qt510/mkspecs/features/lex.prf \
		WebKit.pro
	$(QMAKE) -o Makefile WebKit.pro
/opt/qt510/mkspecs/features/spec_pre.prf:
/opt/qt510/mkspecs/common/unix.conf:
/opt/qt510/mkspecs/common/linux.conf:
/opt/qt510/mkspecs/common/sanitize.conf:
/opt/qt510/mkspecs/common/gcc-base.conf:
/opt/qt510/mkspecs/common/gcc-base-unix.conf:
/opt/qt510/mkspecs/common/g++-base.conf:
/opt/qt510/mkspecs/common/g++-unix.conf:
/opt/qt510/mkspecs/qconfig.pri:
/opt/qt510/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt510/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_core.pri:
/opt/qt510/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt510/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_glx_support_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_gui.pri:
/opt/qt510/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_location.pri:
/opt/qt510/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt510/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt510/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_network.pri:
/opt/qt510/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt510/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt510/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt510/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt510/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_qml.pri:
/opt/qt510/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt510/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_quick.pri:
/opt/qt510/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/qt510/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt510/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_script.pri:
/opt/qt510/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt510/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt510/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_sql.pri:
/opt/qt510/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt510/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt510/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_webengine.pri:
/opt/qt510/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/qt510/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/qt510/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt510/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_xml.pri:
/opt/qt510/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt510/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt510/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt510/mkspecs/features/qt_functions.prf:
/opt/qt510/mkspecs/features/qt_config.prf:
/opt/qt510/mkspecs/linux-g++/qmake.conf:
/opt/qt510/mkspecs/features/spec_post.prf:
/opt/qt510/mkspecs/qmodule.pri:
/opt/qt510/mkspecs/features/qt_build_config.prf:
.qmake.conf:
/opt/qt510/mkspecs/features/exclusive_builds.prf:
/opt/qt510/mkspecs/features/toolchain.prf:
/opt/qt510/mkspecs/features/default_pre.prf:
Tools/qmake/mkspecs/features/functions.prf:
/opt/qt510/mkspecs/features/resolve_config.prf:
/opt/qt510/mkspecs/features/default_post.prf:
/opt/qt510/mkspecs/features/exceptions_off.prf:
/opt/qt510/mkspecs/features/qt_example_installs.prf:
/opt/qt510/mkspecs/features/qt_docs_targets.prf:
/opt/qt510/mkspecs/features/unix/largefile.prf:
/opt/qt510/mkspecs/features/warn_on.prf:
/opt/qt510/mkspecs/features/qmake_use.prf:
/opt/qt510/mkspecs/features/file_copies.prf:
/opt/qt510/mkspecs/features/qt_build_extra.prf:
/opt/qt510/mkspecs/features/testcase_targets.prf:
/opt/qt510/mkspecs/features/yacc.prf:
/opt/qt510/mkspecs/features/lex.prf:
WebKit.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile WebKit.pro

qmake_all: FORCE

make_first:  FORCE
all:  FORCE
clean:  FORCE
distclean:  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: FORCE
uninstall_subtargets: FORCE

html_docs:
	$(MAKE) -f $(MAKEFILE) prepare_docs && $(MAKE) -f $(MAKEFILE) generate_docs

docs:
	$(MAKE) -f $(MAKEFILE) html_docs && $(MAKE) -f $(MAKEFILE) qch_docs

install_html_docs:

uninstall_html_docs:

install_qch_docs:

uninstall_qch_docs:

install_docs:

uninstall_docs:

qch_docs:

prepare_docs:

generate_docs:

check:

benchmark:
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents .qmake.conf Tools/qmake/mkspecs/features/functions.prf WebKit.pro $(DISTDIR)/

